INSERT INTO user_details(ID,BIRTH_DATE,NAME) VALUES(1001,current_date(),'ABELLEGA STEPHEN');
INSERT INTO user_details(ID,BIRTH_DATE,NAME) VALUES(1002,current_date(),'FANEN PAVEUN');
INSERT INTO user_details(ID,BIRTH_DATE,NAME) VALUES(1003,current_date(),'EUGENE OMOGO');